import type { Metadata } from "next";
import { auth } from "@/server/auth/auth";
import { redirect } from "next/navigation";

export const metadata: Metadata = {
  title: "Home",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await auth();

  if (!session) return redirect("/api/signInRedirect");

  return children;
}
