import { routing } from "@/server/i18n/routing";
import type { Metadata } from "next";
import { auth } from "@/server/auth/auth";
import LoginRedirect from "@/components/common/LoginRedirect";

export const metadata: Metadata = {
  title: "MB Infocus",
  description: "Generated by create next app",
};

export function generateStaticParams() {
  return routing.locales.map((locale) => ({ locale }));
}

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await auth();

  if (!session)
    return (
      <html lang="en">
        <head />
        <body>
          <LoginRedirect />
        </body>
      </html>
    );

  return <>{children}</>;
}
